import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import ThemeContextProvider from '@/contexts/theme-context';
import FilterContextProvider from '@/contexts/filter-context';

const nunito_sans = Nunito_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${nunito_sans.className} bg-bg-light dark:bg-bg-dark`}>
				<ThemeContextProvider>
					<Header />
					<FilterContextProvider>{children}</FilterContextProvider>
				</ThemeContextProvider>
			</body>
		</html>
	);
}
